### ISSUE TITLE
Source Code Updates?

### ISSUE THREAD

**Issue by kiwids0220** [0vercl0k/lockmem#5]
Greetings! I was trying to re-use the code to lock a process' memory in my harness. But after porting the code. I ran into issues like shown below:

![image](https://github.com/0vercl0k/lockmem/assets/60630639/68234fb3-7faa-4412-a1f0-c1a912159292)

And If I run the released .exe, which works just fine xD. So not sure if this is the most up-to-date source...
![image](https://github.com/0vercl0k/lockmem/assets/60630639/21fc6358-dcba-4cea-b181-9daaa596a9e9)

Thank you!

**Comment by 0vercl0k** [comment]
Let me take a look at this in December - I am currently on vacation, sorry!

Cheers

**Comment by kiwids0220** [comment]
Please take the time off for as long as you need, no rush here! Thanks alot!
> Let me take a look at this in December - I am currently on vacation, sorry!
> 
> 
> 
> Cheers
> 
> 
>

**Comment by 0vercl0k** [comment]
I just took a look at this - it seems that maybe you are not reading the latest version of the source code?

Those `printf` calls are commented: https://github.com/0vercl0k/lockmem/blob/v0.2/src/lockmem.cc#L133

Or I misunderstood the question :)

Cheers

**Comment by 0vercl0k** [comment]
Feel free to re-open if I misunderstood :)

Cheers
